### ISSUE TITLE
Request: framebuffer support for arduino compatible controllers with more RAM

### ISSUE THREAD

**Issue by mattncsu** [soonuse/epd-library-arduino#1]
I noticed the comment in the [2.9b sketch](https://github.com/soonuse/gdew029z10_2.9inch_e-paper_b/blob/master/arduino/libraries/epd2in9b.cpp)
  /**
    * Due to RAM not enough in Arduino UNO, a frame buffer is not allowed.
    * In this case, a smaller image buffer is allocated and you have to 
    * update a partial display several times.
    * 1 byte = 8 pixels, therefore you have to set 8*N pixels at a time.
    */

Can a frame buffer be used for AVR chips with more RAM such as ATxmega series or Arduino-compatible boards such as the ESP8266/ESP32 which have plenty of RAM compared to an UNO?

Does the code take advantage of microcontrollers with additional RAM, and if not, could it be modified to do so?

**Comment by soonuse** [comment]
1. ATxmega --> I tried ATxmega but of which RAM is not enough too.
2. Probably yes, for example, we don't have to think about the RAM limit on Raspberry Pi. See: https://github.com/soonuse/epd-library-wiringpi
