### ISSUE TITLE
Bug in epdif.cpp

### ISSUE THREAD

**Issue by psitech** [soonuse/epd-library-arduino#2]
In epd-library-arduino/2.9inch_e-paper/arduino/libraries/epdif.cpp, the following 2 lines must be swapped:
60   SPI.beginTransaction(SPISettings(2000000, MSBFIRST, SPI_MODE0));
61   SPI.begin();
otherwise the SPI bus won't work [as I found out when trying to get the 2.9" display to work].
So the correct sequence is:
60   SPI.begin();
61   SPI.beginTransaction(SPISettings(2000000, MSBFIRST, SPI_MODE0));

Regards,
Paul

**Comment by soonuse** [comment]
Thank you for your report.

**Comment by psitech** [comment]
Hi Yehui,
Thanks for fixing the libraries.
However, the downloadable sources on the Waveshare website have not yet been updated with this fix.
Do you also take care of that?

Thanks,
Paul

**Comment by soonuse** [comment]
All right, it's updated now.

**Comment by psitech** [comment]
Thanks.
