### ISSUE TITLE
Arduino Mega Support

### ISSUE THREAD

**Issue by pmcanseco** [soonuse/epd-library-arduino#6]
Hello,

I've been trying to get my Waveshare epaper 1.54" screen working on an Arduino Mega. I've been successful but I had to make a modification to the library.

https://github.com/soonuse/epd-library-arduino/blob/master/1.54inch_e-paper/arduino/libraries/epdif.h#L36

In the above file, Line 36 needs to be changed from 10 to 53 because the screen communicates via SPI, and the SS pin for SPI communications on the Mega is on pin 53 whereas it is pin 10 on the Uno. That's it for the code changes.

Additionally, I needed to change the wiring:
 - SCK (uno pin 13) to mega pin 52
 - MOSI (uno pin 11) to mega pin 51
 - SS (uno pin 10) to mega pin 53

After doing the above, the screen worked flawlessly in my Mega. It would be helpful if the library files could detect whether they're being compiled for the uno or mega and update the pin definitions in epdif.h accordingly. Also helpful would be documentation updates to include how to wire the screen up for the mega. 

Thank you!

**Comment by soonuse** [comment]
Thank you for your suggestion. It's very helpful.
