### ISSUE TITLE
2.13inch D support

### ISSUE THREAD

**Issue by sriranjanr** [soonuse/epd-library-arduino#7]
I have the flexible 2.13 eink display from waveshare which you marked at 2.13" D display. I was able together display from waveshare to work with your code but not the 2.13"D. Could you tell me how to get this working?

**Comment by soonuse** [comment]
I was no  longer maintain the e-paper display models. And you can get it just from Waveshare Wiki:
https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT_(D)
I wonder which code you mentioned is not working? I can tell my coworker to fix it.
