### ISSUE TITLE
Libraries not found

### ISSUE THREAD

**Issue by ninfan** [soonuse/epd-library-arduino#8]
Hello i always get this error
epd2in13b-demo:28:23: error: epd2in13b.h: No such file or directory

If i do like the readme:
1.Copy the libraries (e-paper/arduino/libraries) of Arduino demo code to the libraries directory of Arduino IDE. (C:\users\username\documents\arduino\libraries by default. You can also specify the location on Arduino IDE --> File --> Preferences --> Sketchbook location).

2.Open the project (arduino/epd-demo/epd-demo.ino)
Compile and upload the program.

So i copied all files from libraries folder to the arduino/libraries

Please tell me the correct folder path beginning from arduino IDE folder to epd2in13b.h file

**Comment by soonuse** [comment]
First please make sure you've copied the directory (the directory epd2in13b) to arduino/libraries, i.e. arduino/libraries/epd2in13b, but not arduino/libraries/epd2in13b.h. Then I wonder the version of your Arduino IDE since it works fine on Arduino 1.8.5.
